"""esquema inicial completo

Revision ID: 36c910f133c5
Revises: 
Create Date: 2026-08-14 07:28:16.751358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '36c910f133c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # PostGIS antes que cualquier tabla: hay columnas geometry(Point, 4326)
    # más abajo. La imagen postgis/postgis suele dejar la extensión creada en
    # su base por defecto, pero el despliegue no puede depender de eso — si la
    # base la crea otra persona o con otro nombre, la extensión no está.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'PERSON', 'SYSTEM', 'PARTNER', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('before_redacted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_redacted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('previous_hash', sa.LargeBinary(), nullable=True),
    sa.Column('event_hash', sa.LargeBinary(), nullable=False),
    sa.Column('anchor_object_uri', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash')
    )
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_table('channels',
    sa.Column('type', sa.Enum('WHATSAPP', 'WEB', 'API', name='channel_type'), nullable=False),
    sa.Column('provider', sa.Enum('META_CLOUD_API', 'INTERNAL_WEB', 'PARTNER_API', name='channel_provider_type'), nullable=False),
    sa.Column('external_account_id', sa.Text(), nullable=True),
    sa.Column('phone_number_id', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('TEST', 'ACTIVE', 'DEGRADED', 'DISABLED', name='channel_status'), nullable=False),
    sa.Column('secret_ref', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_account_id', 'phone_number_id')
    )
    op.create_table('geo_divipola',
    sa.Column('municipality_code', sa.String(length=5), nullable=False),
    sa.Column('department_code', sa.String(length=2), nullable=False),
    sa.Column('department_name', sa.Text(), nullable=False),
    sa.Column('municipality_name', sa.Text(), nullable=False),
    sa.Column('municipality_type', sa.Text(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('municipality_code')
    )
    op.create_index(op.f('ix_geo_divipola_department_code'), 'geo_divipola', ['department_code'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.LargeBinary(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body_redacted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_type', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'key')
    )
    op.create_index(op.f('ix_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False)
    op.create_table('incidents',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'RECOVERY', 'CLOSED', 'ARCHIVED', name='incident_status'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geography', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('policy_version', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_incidents_status_starts', 'incidents', ['status', 'starts_at'], unique=False)
    op.create_table('locations',
    sa.Column('country_code', sa.CHAR(length=2), nullable=False),
    sa.Column('admin1', sa.Text(), nullable=True),
    sa.Column('admin2', sa.Text(), nullable=True),
    sa.Column('admin3', sa.Text(), nullable=True),
    sa.Column('locality_text_enc', sa.LargeBinary(), nullable=True),
    sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('accuracy_m', sa.Numeric(), nullable=True),
    sa.Column('source', sa.Enum('GPS', 'WHATSAPP_LOCATION', 'GEOCODED_TEXT', 'MANUAL', 'IMPORTED', name='location_source'), nullable=False),
    sa.Column('public_geohash', sa.String(length=8), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_locations_admin', 'locations', ['admin1', 'admin2'], unique=False)
    op.create_table('need_catalog',
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name_es', sa.Text(), nullable=False),
    sa.Column('unit_code', sa.String(length=16), nullable=True),
    sa.Column('default_horizon', sa.Enum('EMERGENCY', 'RECOVERY', 'RECONSTRUCTION', name='need_horizon'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('attributes_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['need_catalog.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version')
    )
    op.create_index('ix_need_catalog_parent_active', 'need_catalog', ['parent_id', 'active'], unique=False)
    op.create_table('organizations',
    sa.Column('legal_name_enc', sa.LargeBinary(), nullable=True),
    sa.Column('public_name', sa.Text(), nullable=False),
    sa.Column('org_type', sa.Enum('NGO', 'GOVERNMENT', 'COMPANY', 'COMMUNITY', 'OPERATOR', 'FUNDER', 'LOGISTICS', name='org_type'), nullable=False),
    sa.Column('tax_id_enc', sa.LargeBinary(), nullable=True),
    sa.Column('tax_id_hmac', sa.LargeBinary(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='org_verification_status'), nullable=False),
    sa.Column('contact_email_enc', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'ARCHIVED', name='org_record_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_name', 'org_type')
    )
    op.create_index(op.f('ix_organizations_tax_id_hmac'), 'organizations', ['tax_id_hmac'], unique=False)
    op.create_table('outbox_events',
    sa.Column('aggregate_type', sa.Text(), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('payload_redacted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('publish_status', sa.Enum('PENDING', 'PUBLISHED', 'RETRY', 'DEAD_LETTER', name='outbox_status'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_redacted', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_events_status_next_attempt', 'outbox_events', ['publish_status', 'next_attempt_at'], unique=False)
    op.create_index('ix_outbox_events_status_occurred', 'outbox_events', ['publish_status', 'occurred_at'], unique=False)
    op.create_table('persons',
    sa.Column('display_name_enc', sa.LargeBinary(), nullable=True),
    sa.Column('preferred_name_enc', sa.LargeBinary(), nullable=True),
    sa.Column('birth_date_enc', sa.LargeBinary(), nullable=True),
    sa.Column('gender_optional_enc', sa.LargeBinary(), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('vulnerability_flags_enc', sa.LargeBinary(), nullable=True),
    sa.Column('deceased_flag', sa.Boolean(), nullable=False),
    sa.Column('data_status', sa.Enum('PARTIAL', 'CONFIRMED', 'MERGED', 'RESTRICTED', 'DELETED_TOMBSTONE', name='person_data_status'), nullable=False),
    sa.Column('name_dedupe_hmac', sa.LargeBinary(), nullable=True),
    sa.Column('merged_into_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_name_dedupe_hmac'), 'persons', ['name_dedupe_hmac'], unique=False)
    op.create_table('roles',
    sa.Column('code', sa.Enum('AFFECTED_SELF_SERVICE', 'REPORTER', 'COMMUNITY_LEADER', 'VOLUNTEER', 'VALIDATOR', 'DONOR', 'COMPANY_REP', 'ORG_OPERATOR', 'AGENT', 'SUPERVISOR', 'AUDITOR', 'ADMIN', name='role_code'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('system_managed', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version')
    )
    op.create_table('consents',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.Enum('CASE_MANAGEMENT', 'CONTACT', 'AI_PROCESSING', 'LOCATION', 'PUBLICATION', 'DATA_SHARING', name='consent_purpose'), nullable=False),
    sa.Column('notice_version', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('GRANTED', 'DENIED', 'REVOKED', 'EXPIRED', 'EXCEPTION_REVIEW', name='consent_status'), nullable=False),
    sa.Column('captured_via', sa.Enum('WHATSAPP', 'WEB', 'API', name='consent_channel_type'), nullable=False),
    sa.Column('proof_message_id', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consents_person_purpose', 'consents', ['person_id', 'purpose', 'status'], unique=False)
    op.create_table('conversations',
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('external_thread_key_hmac', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'WAITING_USER', 'WAITING_SYSTEM', 'AGENT_HANDOFF', 'SNOOZED', 'CLOSED', name='conversation_status'), nullable=False),
    sa.Column('primary_intent', sa.Enum('NEED_HELP', 'REPORT_FOR_OTHERS', 'OFFER_HELP', 'TRACK_CASE', 'OTHER', name='conversation_intent'), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('active_case_id', sa.Uuid(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_mode', sa.Enum('BOT', 'COPILOT', 'HUMAN', name='agent_mode'), nullable=False),
    sa.Column('context_summary_enc', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_channel_thread_status', 'conversations', ['channel_id', 'external_thread_key_hmac', 'status'], unique=False)
    op.create_index('ix_conversations_last_message_status', 'conversations', ['last_message_at', 'status'], unique=False)
    op.create_table('households',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('reference_code', sa.String(length=32), nullable=False),
    sa.Column('head_person_id', sa.Uuid(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('minors_count', sa.Integer(), nullable=True),
    sa.Column('older_adults_count', sa.Integer(), nullable=True),
    sa.Column('disability_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'MERGED', 'CLOSED', 'RESTRICTED', name='household_status'), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('member_count IS NULL OR minors_count IS NULL OR member_count >= minors_count', name='ck_households_counts_coherent'),
    sa.ForeignKeyConstraint(['head_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'reference_code')
    )
    op.create_table('notifications',
    sa.Column('recipient_person_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('template_code', sa.Text(), nullable=False),
    sa.Column('template_version', sa.Text(), nullable=False),
    sa.Column('variables_enc', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'SCHEDULED', 'SENT', 'DELIVERED', 'READ', 'FAILED', 'CANCELLED', 'SUPPRESSED', name='notification_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['recipient_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_notifications_status_scheduled', 'notifications', ['status', 'scheduled_at'], unique=False)
    op.create_table('person_identifiers',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('PHONE', 'NATIONAL_ID', 'PASSPORT', 'EMAIL', 'BANK_ACCOUNT', 'OTHER', name='identifier_type'), nullable=False),
    sa.Column('value_enc', sa.LargeBinary(), nullable=False),
    sa.Column('value_hmac', sa.LargeBinary(), nullable=False),
    sa.Column('last4', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issuer', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value_hmac')
    )
    op.create_index('ix_person_identifiers_person_primary', 'person_identifiers', ['person_id', 'is_primary'], unique=False)
    op.create_table('public_impact_snapshots',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('geography_level', sa.Text(), nullable=False),
    sa.Column('geography_code', sa.Text(), nullable=False),
    sa.Column('metric_code', sa.Text(), nullable=False),
    sa.Column('dimension_json', sa.Text(), nullable=False),
    sa.Column('value_numeric', sa.Numeric(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('privacy_threshold', sa.Integer(), nullable=True),
    sa.Column('suppression_applied', sa.Boolean(), nullable=False),
    sa.Column('source_run_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'geography_level', 'geography_code', 'metric_code', 'dimension_json', 'as_of')
    )
    op.create_table('resource_offers',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('donor_person_id', sa.Uuid(), nullable=True),
    sa.Column('donor_org_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('MONEY', 'IN_KIND', 'SERVICE', 'TRANSPORT', 'VOLUNTEERING', name='resource_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_CONFIRMATION', 'AVAILABLE', 'PARTIALLY_ALLOCATED', 'FULLY_ALLOCATED', 'EXPIRED', 'WITHDRAWN', 'BLOCKED', name='offer_status'), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_location_id', sa.Uuid(), nullable=True),
    sa.Column('destination_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allocation_preference', sa.Enum('SPECIFIC_CASE', 'HIGHEST_NEED', 'OPERATOR_DECIDES', name='allocation_preference'), nullable=False),
    sa.Column('notes_enc', sa.LargeBinary(), nullable=True),
    sa.Column('trust_review_state', sa.Enum('NONE', 'PENDING', 'IN_REVIEW', 'CLEARED', 'ESCALATED', name='trust_review_state'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['donor_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['donor_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['origin_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resource_offers_incident_type_status', 'resource_offers', ['incident_id', 'type', 'status', 'available_from'], unique=False)
    op.create_table('users',
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('identity_provider_sub', sa.Text(), nullable=True),
    sa.Column('email_enc', sa.LargeBinary(), nullable=True),
    sa.Column('email_hmac', sa.LargeBinary(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('totp_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('mfa_enrolled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'LOCKED', 'SUSPENDED', 'DISABLED', name='user_status'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authz_version', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_hmac'),
    sa.UniqueConstraint('identity_provider_sub')
    )
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('webhook_receipts',
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('provider_event_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload_enc', sa.LargeBinary(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.Enum('RECEIVED', 'DUPLICATE', 'QUEUED', 'PROCESSED', 'FAILED', 'DEAD_LETTER', name='webhook_processing_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error_redacted', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'provider_event_id')
    )
    op.create_index('ix_webhook_receipts_status_received', 'webhook_receipts', ['processing_status', 'received_at'], unique=False)
    op.create_table('access_events',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('purpose_code', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('field_classification', sa.Enum('PUB', 'INT', 'PRIV', 'SENS', name='data_class'), nullable=True),
    sa.Column('action', sa.Enum('VIEW', 'SEARCH', 'DOWNLOAD', 'EXPORT', 'DECRYPT', 'BREAK_GLASS', name='access_action'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_hash', sa.LargeBinary(), nullable=True),
    sa.Column('device_hash', sa.LargeBinary(), nullable=True),
    sa.Column('break_glass_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_access_events_actor_occurred', 'access_events', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index('ix_access_events_entity', 'access_events', ['entity_type', 'entity_id'], unique=False)
    op.create_table('agent_queue_items',
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('queue_code', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', name='queue_priority'), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'ASSIGNED', 'IN_PROGRESS', 'SNOOZED', 'RESOLVED', 'CANCELLED', name='queue_item_status'), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('required_skill', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_queue_items_dispatch', 'agent_queue_items', ['queue_code', 'status', 'priority', 'sla_due_at'], unique=False)
    op.create_table('cases',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('case_code', sa.String(length=32), nullable=False),
    sa.Column('case_type', sa.Text(), nullable=True),
    sa.Column('household_id', sa.Uuid(), nullable=True),
    sa.Column('primary_location_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'INCOMPLETE', 'PENDING_VERIFICATION', 'VERIFIED', 'ACTIVE', 'ON_HOLD', 'PARTIALLY_SERVED', 'SERVED', 'CLOSED', 'DUPLICATE', 'REJECTED', 'CANCELLED', 'SUSPICIOUS', name='case_status'), nullable=False),
    sa.Column('priority_band', sa.Enum('P0', 'P1', 'P2', 'P3', name='priority_band'), nullable=True),
    sa.Column('completeness_score', sa.Numeric(), nullable=True),
    sa.Column('trust_review_state', sa.Enum('NONE', 'PENDING', 'IN_REVIEW', 'CLEARED', 'ESCALATED', name='trust_review_state'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['primary_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'case_code')
    )
    op.create_index('ix_cases_incident_status_priority', 'cases', ['incident_id', 'status', 'priority_band'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('participant_type', sa.Enum('CONTACT', 'REPORTER', 'DONOR', 'AGENT', 'BOT', 'SUPERVISOR', name='participant_type'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_participants_conv_joined', 'conversation_participants', ['conversation_id', 'joined_at'], unique=False)
    op.create_index('uq_conversation_participants_active', 'conversation_participants', ['conversation_id', 'participant_type', 'person_id', 'user_id'], unique=True, postgresql_where=sa.text('left_at IS NULL'))
    op.create_table('duplicate_candidates',
    sa.Column('entity_type', sa.Enum('REPORT', 'CASE', 'PERSON', 'MEDIA', name='duplicate_entity_type'), nullable=False),
    sa.Column('left_id', sa.Uuid(), nullable=False),
    sa.Column('right_id', sa.Uuid(), nullable=False),
    sa.Column('algorithm_version', sa.Text(), nullable=False),
    sa.Column('similarity_score', sa.Numeric(), nullable=True),
    sa.Column('matched_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'REVIEWING', 'CONFIRMED', 'NOT_DUPLICATE', 'MERGED', 'DEFERRED', name='duplicate_status'), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('survivor_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_duplicate_candidates_status_score', 'duplicate_candidates', ['status', sa.literal_column('similarity_score DESC')], unique=False)
    op.create_index('uq_duplicate_candidates_pair', 'duplicate_candidates', ['entity_type', sa.literal_column('least(left_id, right_id)'), sa.literal_column('greatest(left_id, right_id)'), 'algorithm_version'], unique=True)
    op.create_table('household_members',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('relationship', sa.Enum('HEAD', 'PARTNER', 'CHILD', 'DEPENDENT', 'RELATIVE', 'NON_RELATIVE', 'UNKNOWN', name='household_relation'), nullable=False),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('source_report_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'person_id', 'valid_from')
    )
    op.create_index('ix_household_members_person', 'household_members', ['person_id', 'valid_to'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('provider_message_id', sa.Text(), nullable=True),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='message_direction'), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'AUDIO', 'IMAGE', 'LOCATION', 'VIDEO', 'DOCUMENT', 'INTERACTIVE', 'SYSTEM', name='message_type'), nullable=False),
    sa.Column('text_enc', sa.LargeBinary(), nullable=True),
    sa.Column('normalized_text_redacted', sa.Text(), nullable=True),
    sa.Column('media_asset_id', sa.Uuid(), nullable=True),
    sa.Column('reply_to_message_id', sa.Uuid(), nullable=True),
    sa.Column('provider_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_status', sa.Enum('QUEUED', 'SENT', 'DELIVERED', 'READ', 'FAILED', name='message_delivery_status'), nullable=True),
    sa.Column('processing_status', sa.Enum('RECEIVED', 'STORED', 'SCANNING', 'READY', 'PROCESSED', 'NEEDS_REVIEW', 'FAILED', name='message_processing_status'), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_message_id')
    )
    op.create_index('ix_messages_conversation_provider_ts', 'messages', ['conversation_id', 'provider_timestamp'], unique=False)
    op.create_table('money_offer_details',
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('pledged_amount', sa.Numeric(), nullable=True),
    sa.Column('max_case_count', sa.Integer(), nullable=True),
    sa.Column('designated_case_id', sa.Uuid(), nullable=True),
    sa.Column('funding_partner_org_id', sa.Uuid(), nullable=True),
    sa.Column('payment_route', sa.Text(), nullable=True),
    sa.Column('settlement_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('pledged_amount > 0', name='ck_money_offer_amount_positive'),
    sa.ForeignKeyConstraint(['funding_partner_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['resource_offers.id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_table('organization_memberships',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('membership_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'SUSPENDED', 'ENDED', name='membership_status'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', 'membership_type')
    )
    op.create_index('ix_org_memberships_user_status', 'organization_memberships', ['user_id', 'status'], unique=False)
    op.create_table('reports',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('reporter_person_id', sa.Uuid(), nullable=True),
    sa.Column('reporter_role', sa.Enum('SELF', 'FAMILY', 'NEIGHBOR', 'COMMUNITY_LEADER', 'OFFICIAL', 'THIRD_PARTY', name='reporter_role'), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'COLLECTING', 'SUBMITTED_INCOMPLETE', 'SUBMITTED', 'LINKED', 'DUPLICATE', 'WITHDRAWN', 'REJECTED', name='report_status'), nullable=False),
    sa.Column('completeness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['reporter_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_incident_status_submitted', 'reports', ['incident_id', 'status', 'submitted_at'], unique=False)
    op.create_table('resource_offer_items',
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_id', sa.Uuid(), nullable=True),
    sa.Column('description_redacted', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('unit_code', sa.Text(), nullable=True),
    sa.Column('condition', sa.Enum('NEW', 'GOOD', 'USED', 'REFURBISHED', 'NOT_APPLICABLE', name='item_condition'), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('reserved_qty', sa.Numeric(), nullable=True),
    sa.Column('delivered_qty', sa.Numeric(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('coalesce(reserved_qty, 0) + coalesce(delivered_qty, 0) <= quantity', name='ck_offer_items_qty'),
    sa.ForeignKeyConstraint(['offer_id'], ['resource_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resource_offer_items_offer_catalog', 'resource_offer_items', ['offer_id', 'catalog_id'], unique=False)
    op.create_table('retention_jobs',
    sa.Column('policy_code', sa.Text(), nullable=False),
    sa.Column('policy_version', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'APPROVED', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED', name='retention_job_status'), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('affected_count', sa.BigInteger(), nullable=True),
    sa.Column('error_count', sa.BigInteger(), nullable=True),
    sa.Column('manifest_uri', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retention_jobs_policy_status', 'retention_jobs', ['policy_code', 'status', 'cutoff_at'], unique=False)
    op.create_table('risk_signals',
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.Text(), nullable=False),
    sa.Column('rule_version', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_severity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'TRIAGED', 'FALSE_POSITIVE', 'MITIGATED', 'CONFIRMED_ISSUE', 'CLOSED', name='risk_status'), nullable=False),
    sa.Column('evidence_json_enc', sa.LargeBinary(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('signal_fingerprint', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code', 'rule_version', 'subject_type', 'subject_id', 'signal_fingerprint')
    )
    op.create_index('ix_risk_signals_incident_status', 'risk_signals', ['incident_id', 'status', 'severity', 'detected_at'], unique=False)
    op.create_table('service_offer_details',
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('service_category', sa.Text(), nullable=False),
    sa.Column('capacity', sa.Numeric(), nullable=True),
    sa.Column('unit_code', sa.Text(), nullable=True),
    sa.Column('credentials_required', sa.Boolean(), nullable=False),
    sa.Column('credentials_evidence_id', sa.Uuid(), nullable=True),
    sa.Column('service_area', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['resource_offers.id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_index(op.f('ix_service_offer_details_service_category'), 'service_offer_details', ['service_category'], unique=False)
    op.create_table('transport_offer_details',
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_type', sa.Text(), nullable=True),
    sa.Column('capacity_weight_kg', sa.Numeric(), nullable=True),
    sa.Column('capacity_volume_m3', sa.Numeric(), nullable=True),
    sa.Column('origin_location_id', sa.Uuid(), nullable=True),
    sa.Column('service_area', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('cold_chain', sa.Boolean(), nullable=False),
    sa.Column('hazardous_allowed', sa.Boolean(), nullable=False),
    sa.Column('driver_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['resource_offers.id'], ),
    sa.ForeignKeyConstraint(['origin_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_index('ix_transport_offer_flags', 'transport_offer_details', ['cold_chain', 'hazardous_allowed'], unique=False)
    op.create_table('trust_assessments',
    sa.Column('subject_type', sa.Enum('REPORTER', 'CASE', 'OFFER', 'DELIVERY', name='trust_subject_type'), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('band', sa.Enum('LOW_EVIDENCE', 'STANDARD_REVIEW', 'HIGH_CONFIDENCE', 'ESCALATED', name='trust_band'), nullable=False),
    sa.Column('component_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_evidence', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['trust_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trust_assessments_subject', 'trust_assessments', ['subject_type', 'subject_id', 'effective_at'], unique=False)
    op.create_table('user_role_assignments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('geography_scope', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_role_user_incident', 'user_role_assignments', ['user_id', 'incident_id'], unique=False)
    op.create_table('volunteer_offer_details',
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('availability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_hours', sa.Numeric(), nullable=True),
    sa.Column('service_area', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('background_check_status', sa.Enum('NOT_REQUIRED', 'PENDING', 'PASSED', 'FAILED', 'EXPIRED', name='check_status'), nullable=False),
    sa.Column('safeguarding_training_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['resource_offers.id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_index('ix_volunteer_offer_skills', 'volunteer_offer_details', ['skills'], unique=False, postgresql_using='gin')
    op.create_table('agent_assignments',
    sa.Column('queue_item_id', sa.Uuid(), nullable=False),
    sa.Column('agent_user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['queue_item_id'], ['agent_queue_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_assignments_agent_released', 'agent_assignments', ['agent_user_id', 'released_at'], unique=False)
    op.create_index('uq_agent_assignments_active_item', 'agent_assignments', ['queue_item_id'], unique=True, postgresql_where=sa.text('released_at IS NULL'))
    op.create_table('ai_extraction_runs',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.Enum('TRANSCRIBE', 'EXTRACT_CASE', 'EXTRACT_OFFER', 'SUMMARIZE', 'DUPLICATE_HINT', 'IMAGE_TRIAGE', 'REDACT', name='ai_task_type'), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.LargeBinary(), nullable=False),
    sa.Column('output_json_enc', sa.LargeBinary(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('safety_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_units', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'SUPERSEDED', name='ai_run_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('input_hash', 'task_type', 'model_version', 'prompt_version')
    )
    op.create_index('ix_ai_runs_message_task_created', 'ai_extraction_runs', ['message_id', 'task_type', 'created_at'], unique=False)
    op.create_table('case_persons',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('AFFECTED', 'REPORTER', 'CAREGIVER', 'BENEFICIARY_CONTACT', 'COMMUNITY_LEADER', 'RECEIVER', 'WITNESS', name='case_person_role'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_report_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['source_report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'person_id', 'role', 'valid_from')
    )
    op.create_index('ix_case_persons_person_role', 'case_persons', ['person_id', 'role'], unique=False)
    op.create_table('case_status_history',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('DRAFT', 'INCOMPLETE', 'PENDING_VERIFICATION', 'VERIFIED', 'ACTIVE', 'ON_HOLD', 'PARTIALLY_SERVED', 'SERVED', 'CLOSED', 'DUPLICATE', 'REJECTED', 'CANCELLED', 'SUSPICIOUS', name='case_status'), nullable=True),
    sa.Column('to_status', sa.Enum('DRAFT', 'INCOMPLETE', 'PENDING_VERIFICATION', 'VERIFIED', 'ACTIVE', 'ON_HOLD', 'PARTIALLY_SERVED', 'SERVED', 'CLOSED', 'DUPLICATE', 'REJECTED', 'CANCELLED', 'SUSPICIOUS', name='case_status'), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('note_redacted', sa.Text(), nullable=True),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_status_history_case_changed', 'case_status_history', ['case_id', 'changed_at'], unique=False)
    op.create_table('matches',
    sa.Column('need_id', sa.Uuid(), nullable=False),
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('offer_item_id', sa.Uuid(), nullable=True),
    sa.Column('algorithm_version', sa.Text(), nullable=False),
    sa.Column('eligibility_passed', sa.Boolean(), nullable=True),
    sa.Column('rejection_reasons', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('humanitarian_priority_score', sa.Numeric(), nullable=True),
    sa.Column('feasibility_score', sa.Numeric(), nullable=True),
    sa.Column('final_rank', sa.Numeric(), nullable=True),
    sa.Column('explanation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'REVIEW_REQUIRED', 'APPROVED', 'REJECTED', 'EXPIRED', 'SUPERSEDED', name='match_status'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['resource_offers.id'], ),
    sa.ForeignKeyConstraint(['offer_item_id'], ['resource_offer_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_matches_need_status_rank', 'matches', ['need_id', 'status', 'final_rank'], unique=False)
    op.create_index('ix_matches_offer_status_rank', 'matches', ['offer_id', 'status', 'final_rank'], unique=False)
    op.create_index('uq_matches_active_pair', 'matches', ['need_id', 'offer_id', 'offer_item_id', 'algorithm_version'], unique=True, postgresql_where=sa.text("status IN ('PROPOSED', 'REVIEW_REQUIRED', 'APPROVED')"))
    op.create_table('media_assets',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('bucket_class', sa.Enum('QUARANTINE', 'PROTECTED', 'PUBLIC_DERIVATIVE', 'AUDIT', name='storage_classification'), nullable=False),
    sa.Column('object_uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.LargeBinary(), nullable=True),
    sa.Column('perceptual_hash', sa.LargeBinary(), nullable=True),
    sa.Column('malware_status', sa.Enum('PENDING', 'CLEAN', 'INFECTED', 'ERROR', name='malware_status'), nullable=False),
    sa.Column('exif_removed', sa.Boolean(), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_index(op.f('ix_media_assets_perceptual_hash'), 'media_assets', ['perceptual_hash'], unique=False)
    op.create_index(op.f('ix_media_assets_retention_until'), 'media_assets', ['retention_until'], unique=False)
    op.create_table('needs',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_id', sa.Uuid(), nullable=False),
    sa.Column('horizon', sa.Enum('EMERGENCY', 'RECOVERY', 'RECONSTRUCTION', name='need_horizon'), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'NEEDS_CLARIFICATION', 'PENDING_VERIFICATION', 'VERIFIED', 'PUBLICABLE', 'OPEN', 'PARTIALLY_COVERED', 'COVERED', 'IN_TRANSIT', 'DELIVERED_PENDING_VERIFY', 'DELIVERED_VERIFIED', 'CLOSED', 'REJECTED', 'DUPLICATE', 'CANCELLED', name='need_status'), nullable=False),
    sa.Column('requested_qty', sa.Numeric(), nullable=True),
    sa.Column('confirmed_qty', sa.Numeric(), nullable=True),
    sa.Column('covered_qty', sa.Numeric(), nullable=True),
    sa.Column('unit_code', sa.Text(), nullable=True),
    sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='urgency_level'), nullable=True),
    sa.Column('needed_by', sa.Date(), nullable=True),
    sa.Column('priority_score', sa.Numeric(), nullable=True),
    sa.Column('description_redacted', sa.Text(), nullable=True),
    sa.Column('attributes_enc', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('covered_qty IS NULL OR confirmed_qty IS NULL OR covered_qty <= confirmed_qty', name='ck_needs_covered_le_confirmed'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['catalog_id'], ['need_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_needs_case_status', 'needs', ['case_id', 'status'], unique=False)
    op.create_index('ix_needs_catalog_horizon_status', 'needs', ['catalog_id', 'horizon', 'status'], unique=False)
    op.create_table('public_case_profiles',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('display_title', sa.Text(), nullable=False),
    sa.Column('story_summary', sa.Text(), nullable=True),
    sa.Column('coarse_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('household_size_band', sa.Text(), nullable=True),
    sa.Column('cover_media_id', sa.Uuid(), nullable=True),
    sa.Column('progress_percent', sa.Numeric(), nullable=True),
    sa.Column('publication_status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'PUBLISHED', 'PAUSED', 'WITHDRAWN', 'ARCHIVED', name='publication_status'), nullable=False),
    sa.Column('consent_basis', sa.Enum('EXPLICIT_CONSENT', 'LEGAL_BASIS_REVIEWED', name='consent_basis'), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_public_case_profiles_status', 'public_case_profiles', ['publication_status', 'published_at'], unique=False)
    op.create_table('report_subjects',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('household_id', sa.Uuid(), nullable=True),
    sa.Column('subject_type', sa.Enum('PERSON', 'HOUSEHOLD', 'COMMUNITY_ASSET', 'BUSINESS', name='subject_type'), nullable=False),
    sa.Column('relation_to_reporter', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_subjects_case', 'report_subjects', ['case_id'], unique=False)
    op.create_index('uq_report_subjects_subject', 'report_subjects', ['report_id', 'subject_type', sa.literal_column('coalesce(case_id, person_id, household_id)')], unique=True)
    op.create_table('allocations',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'RESERVED', 'DONOR_CONFIRMED', 'ACCEPTED_BY_OPERATOR', 'READY_FOR_FULFILLMENT', 'IN_FULFILLMENT', 'FULFILLED', 'PARTIALLY_FULFILLED', 'EXPIRED', 'CANCELLED', 'DISPUTED', name='allocation_status'), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('donor_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_version', sa.Text(), nullable=True),
    sa.Column('public_acknowledgement_pref', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['resource_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_allocations_expires_status', 'allocations', ['expires_at', 'status'], unique=False)
    op.create_index('ix_allocations_offer_status', 'allocations', ['offer_id', 'status'], unique=False)
    op.create_table('evidence',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('BEFORE_PHOTO', 'DAMAGE_PHOTO', 'DOCUMENT', 'GPS', 'VALIDATION_NOTE', 'PICKUP_PROOF', 'DELIVERY_PHOTO', 'RECEIPT', 'AFTER_PHOTO', 'SIGNATURE', name='evidence_type'), nullable=False),
    sa.Column('media_asset_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_by_person_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'TAMPER_ALERT', name='evidence_status'), nullable=False),
    sa.Column('visibility', sa.Enum('PROTECTED', 'AUDITOR_ONLY', 'PUBLIC_DERIVATIVE', name='evidence_visibility'), nullable=False),
    sa.Column('redacted_derivative_id', sa.Uuid(), nullable=True),
    sa.Column('integrity_hash', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['redacted_derivative_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integrity_hash')
    )
    op.create_index('ix_evidence_incident_type_status', 'evidence', ['incident_id', 'type', 'verification_status'], unique=False)
    op.create_table('extraction_candidates',
    sa.Column('ai_run_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_type', sa.Text(), nullable=False),
    sa.Column('field_path', sa.Text(), nullable=False),
    sa.Column('proposed_value_enc', sa.LargeBinary(), nullable=True),
    sa.Column('normalized_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('provenance_offsets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'CONFIRMED', 'CORRECTED', 'REJECTED', 'DEFERRED', name='candidate_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_extraction_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extraction_candidates_entity_field', 'extraction_candidates', ['target_entity_type', 'field_path'], unique=False)
    op.create_index('ix_extraction_candidates_run_status', 'extraction_candidates', ['ai_run_id', 'status'], unique=False)
    op.create_table('need_status_history',
    sa.Column('need_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('REPORTED', 'NEEDS_CLARIFICATION', 'PENDING_VERIFICATION', 'VERIFIED', 'PUBLICABLE', 'OPEN', 'PARTIALLY_COVERED', 'COVERED', 'IN_TRANSIT', 'DELIVERED_PENDING_VERIFY', 'DELIVERED_VERIFIED', 'CLOSED', 'REJECTED', 'DUPLICATE', 'CANCELLED', name='need_status'), nullable=True),
    sa.Column('to_status', sa.Enum('REPORTED', 'NEEDS_CLARIFICATION', 'PENDING_VERIFICATION', 'VERIFIED', 'PUBLICABLE', 'OPEN', 'PARTIALLY_COVERED', 'COVERED', 'IN_TRANSIT', 'DELIVERED_PENDING_VERIFY', 'DELIVERED_VERIFIED', 'CLOSED', 'REJECTED', 'DUPLICATE', 'CANCELLED', name='need_status'), nullable=False),
    sa.Column('quantity_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['need_id'], ['needs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_need_status_history_need_changed', 'need_status_history', ['need_id', 'changed_at'], unique=False)
    op.create_table('public_story_items',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('NEED', 'UPDATE', 'MATCH', 'DELIVERY', 'BEFORE_AFTER', 'COMPLETION', name='story_item_type'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('cta_type', sa.Enum('HELP_THIS_CASE', 'HELP_HIGHEST_NEED', 'OFFER_RESOURCE', 'SHARE', name='cta_type'), nullable=True),
    sa.Column('cta_target', sa.Text(), nullable=True),
    sa.Column('sort_key', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'PUBLISHED', 'PAUSED', 'WITHDRAWN', 'ARCHIVED', name='publication_status'), nullable=False),
    sa.Column('moderation_state', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'FLAGGED', name='moderation_state'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['public_case_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_public_story_items_profile', 'public_story_items', ['profile_id'], unique=False)
    op.create_index('ix_public_story_items_status_sort', 'public_story_items', ['status', 'sort_key'], unique=False)
    op.create_table('allocation_items',
    sa.Column('allocation_id', sa.Uuid(), nullable=False),
    sa.Column('offer_item_id', sa.Uuid(), nullable=False),
    sa.Column('need_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_qty', sa.Numeric(), nullable=False),
    sa.Column('fulfilled_qty', sa.Numeric(), nullable=True),
    sa.Column('unit_code', sa.Text(), nullable=True),
    sa.Column('unit_value_ref', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fulfilled_qty <= allocated_qty', name='ck_allocation_items_fulfilled'),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ),
    sa.ForeignKeyConstraint(['offer_item_id'], ['resource_offer_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allocation_id', 'offer_item_id', 'need_id')
    )
    op.create_table('content_reports',
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('story_item_id', sa.Uuid(), nullable=True),
    sa.Column('reason_code', sa.Text(), nullable=False),
    sa.Column('details_redacted', sa.Text(), nullable=True),
    sa.Column('reporter_contact_enc', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'REVIEWING', 'ACTIONED', 'DISMISSED', name='content_report_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('profile_id IS NOT NULL OR story_item_id IS NOT NULL', name='ck_content_reports_target_present'),
    sa.ForeignKeyConstraint(['profile_id'], ['public_case_profiles.id'], ),
    sa.ForeignKeyConstraint(['story_item_id'], ['public_story_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_reports_status_created', 'content_reports', ['status', 'created_at'], unique=False)
    op.create_table('evidence_links',
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('CASE', 'NEED', 'VALIDATION', 'OFFER', 'SHIPMENT', 'DELIVERY', 'PERSON_CREDENTIAL', name='evidence_entity_type'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.Enum('SUPPORTS', 'BEFORE', 'AFTER', 'RECEIPT', 'IDENTITY', 'TECHNICAL', name='evidence_relation'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'entity_type', 'entity_id', 'relation')
    )
    op.create_index('ix_evidence_links_entity', 'evidence_links', ['entity_type', 'entity_id'], unique=False)
    op.create_table('external_payment_refs',
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('allocation_id', sa.Uuid(), nullable=True),
    sa.Column('partner_org_id', sa.Uuid(), nullable=True),
    sa.Column('external_reference_enc', sa.LargeBinary(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), nullable=True),
    sa.Column('status', sa.Enum('INITIATED', 'PENDING', 'CONFIRMED', 'FAILED', 'REFUNDED', 'DISPUTED', 'UNKNOWN', name='payment_ref_status'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciliation_hash', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['resource_offers.id'], ),
    sa.ForeignKeyConstraint(['partner_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_org_id', 'reconciliation_hash')
    )
    op.create_index('ix_external_payment_refs_status_settled', 'external_payment_refs', ['status', 'settled_at'], unique=False)
    op.create_table('human_confirmations',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('actor_person_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Enum('ACCEPT', 'CORRECT', 'REJECT', 'CANNOT_CONFIRM', name='confirmation_decision'), nullable=False),
    sa.Column('corrected_value_enc', sa.LargeBinary(), nullable=True),
    sa.Column('confirmation_message_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['extraction_candidates.id'], ),
    sa.ForeignKeyConstraint(['confirmation_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_human_confirmations_candidate_decided', 'human_confirmations', ['candidate_id', 'decided_at'], unique=False)
    op.create_table('shipments',
    sa.Column('allocation_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_code', sa.String(length=32), nullable=False),
    sa.Column('operator_org_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'READY', 'PICKED_UP', 'IN_TRANSIT', 'DELAYED', 'ARRIVED', 'PARTIALLY_DELIVERED', 'DELIVERED', 'LOST', 'CANCELLED', name='shipment_status'), nullable=False),
    sa.Column('planned_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracking_ref_enc', sa.LargeBinary(), nullable=True),
    sa.Column('cold_chain_required', sa.Boolean(), nullable=False),
    sa.Column('custody_status', sa.Enum('NOT_STARTED', 'ACTIVE', 'BROKEN', 'COMPLETE', name='custody_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ),
    sa.ForeignKeyConstraint(['operator_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_code')
    )
    op.create_index('ix_shipments_status_planned_arrival', 'shipments', ['status', 'planned_arrival'], unique=False)
    op.create_table('validations',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('need_id', sa.Uuid(), nullable=True),
    sa.Column('validator_user_id', sa.Uuid(), nullable=True),
    sa.Column('validator_org_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('DOCUMENT', 'PHONE', 'COMMUNITY', 'REMOTE_MEDIA', 'FIELD_VISIT', 'TECHNICAL', name='validation_type'), nullable=False),
    sa.Column('outcome', sa.Enum('PASS', 'PARTIAL', 'FAIL', 'INCONCLUSIVE', 'EXPIRED', name='validation_outcome'), nullable=True),
    sa.Column('checklist_version', sa.Text(), nullable=True),
    sa.Column('findings_enc', sa.LargeBinary(), nullable=True),
    sa.Column('evidence_id', sa.Uuid(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['need_id'], ['needs.id'], ),
    sa.ForeignKeyConstraint(['validator_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['validator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_validations_case_type_performed', 'validations', ['case_id', 'type', 'performed_at'], unique=False)
    op.create_index('ix_validations_need_outcome', 'validations', ['need_id', 'outcome'], unique=False)
    op.create_table('deliveries',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_person_id', sa.Uuid(), nullable=True),
    sa.Column('receiving_org_id', sa.Uuid(), nullable=True),
    sa.Column('delivery_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'ARRIVING', 'HANDED_OVER_PENDING_PROOF', 'PROOF_SUBMITTED', 'VERIFIED', 'PARTIAL', 'REJECTED', 'DISPUTED', 'FAILED', 'CANCELLED', name='delivery_state'), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_method', sa.Enum('OTP', 'QR', 'SIGNATURE', 'PHOTO', 'AGENT_ATTESTATION', 'PARTNER_CONFIRMATION', name='receipt_method'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispute_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['receiving_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['recipient_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_code')
    )
    op.create_index('ix_deliveries_case_status', 'deliveries', ['case_id', 'status'], unique=False)
    op.create_index('ix_deliveries_delivered_status', 'deliveries', ['delivered_at', 'status'], unique=False)
    op.create_table('shipment_stops',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('stop_type', sa.Enum('ORIGIN', 'HUB', 'HANDOFF', 'DESTINATION', name='stop_type'), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('contact_person_id', sa.Uuid(), nullable=True),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof_evidence_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ARRIVED', 'COMPLETED', 'SKIPPED', 'FAILED', name='stop_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['proof_evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'sequence_no')
    )
    op.create_index('ix_shipment_stops_location_planned', 'shipment_stops', ['location_id', 'planned_at'], unique=False)
    op.create_table('delivery_items',
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('allocation_item_id', sa.Uuid(), nullable=False),
    sa.Column('delivered_qty', sa.Numeric(), nullable=False),
    sa.Column('accepted_qty', sa.Numeric(), nullable=True),
    sa.Column('rejected_qty', sa.Numeric(), nullable=True),
    sa.Column('condition_note', sa.Text(), nullable=True),
    sa.Column('serial_or_lot_enc', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('accepted_qty IS NULL OR rejected_qty IS NULL OR delivered_qty >= accepted_qty + rejected_qty', name='ck_delivery_items_qty_coherent'),
    sa.ForeignKeyConstraint(['allocation_item_id'], ['allocation_items.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id', 'allocation_item_id')
    )
    op.create_table('delivery_receipts',
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.Enum('OTP', 'QR', 'SIGNATURE', 'PHOTO', 'AGENT_ATTESTATION', 'PARTNER_CONFIRMATION', name='receipt_method'), nullable=False),
    sa.Column('receiver_person_id', sa.Uuid(), nullable=True),
    sa.Column('otp_hash', sa.LargeBinary(), nullable=True),
    sa.Column('signature_object_uri', sa.Text(), nullable=True),
    sa.Column('witness_user_id', sa.Uuid(), nullable=True),
    sa.Column('result', sa.Enum('VALID', 'INVALID', 'EXPIRED', 'OVERRIDDEN_WITH_REASON', name='receipt_result'), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_context_enc', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['receiver_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['witness_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_delivery_receipts_delivery_captured', 'delivery_receipts', ['delivery_id', 'captured_at'], unique=False)
    op.create_index('uq_delivery_receipts_active_otp', 'delivery_receipts', ['delivery_id'], unique=True, postgresql_where=sa.text('otp_hash IS NOT NULL AND result IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_delivery_receipts_active_otp', table_name='delivery_receipts', postgresql_where=sa.text('otp_hash IS NOT NULL AND result IS NULL'))
    op.drop_index('ix_delivery_receipts_delivery_captured', table_name='delivery_receipts')
    op.drop_table('delivery_receipts')
    op.drop_table('delivery_items')
    op.drop_index('ix_shipment_stops_location_planned', table_name='shipment_stops')
    op.drop_table('shipment_stops')
    op.drop_index('ix_deliveries_delivered_status', table_name='deliveries')
    op.drop_index('ix_deliveries_case_status', table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index('ix_validations_need_outcome', table_name='validations')
    op.drop_index('ix_validations_case_type_performed', table_name='validations')
    op.drop_table('validations')
    op.drop_index('ix_shipments_status_planned_arrival', table_name='shipments')
    op.drop_table('shipments')
    op.drop_index('ix_human_confirmations_candidate_decided', table_name='human_confirmations')
    op.drop_table('human_confirmations')
    op.drop_index('ix_external_payment_refs_status_settled', table_name='external_payment_refs')
    op.drop_table('external_payment_refs')
    op.drop_index('ix_evidence_links_entity', table_name='evidence_links')
    op.drop_table('evidence_links')
    op.drop_index('ix_content_reports_status_created', table_name='content_reports')
    op.drop_table('content_reports')
    op.drop_table('allocation_items')
    op.drop_index('ix_public_story_items_status_sort', table_name='public_story_items')
    op.drop_index('ix_public_story_items_profile', table_name='public_story_items')
    op.drop_table('public_story_items')
    op.drop_index('ix_need_status_history_need_changed', table_name='need_status_history')
    op.drop_table('need_status_history')
    op.drop_index('ix_extraction_candidates_run_status', table_name='extraction_candidates')
    op.drop_index('ix_extraction_candidates_entity_field', table_name='extraction_candidates')
    op.drop_table('extraction_candidates')
    op.drop_index('ix_evidence_incident_type_status', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_allocations_offer_status', table_name='allocations')
    op.drop_index('ix_allocations_expires_status', table_name='allocations')
    op.drop_table('allocations')
    op.drop_index('uq_report_subjects_subject', table_name='report_subjects')
    op.drop_index('ix_report_subjects_case', table_name='report_subjects')
    op.drop_table('report_subjects')
    op.drop_index('ix_public_case_profiles_status', table_name='public_case_profiles')
    op.drop_table('public_case_profiles')
    op.drop_index('ix_needs_catalog_horizon_status', table_name='needs')
    op.drop_index('ix_needs_case_status', table_name='needs')
    op.drop_table('needs')
    op.drop_index(op.f('ix_media_assets_retention_until'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_perceptual_hash'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('uq_matches_active_pair', table_name='matches', postgresql_where=sa.text("status IN ('PROPOSED', 'REVIEW_REQUIRED', 'APPROVED')"))
    op.drop_index('ix_matches_offer_status_rank', table_name='matches')
    op.drop_index('ix_matches_need_status_rank', table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_case_status_history_case_changed', table_name='case_status_history')
    op.drop_table('case_status_history')
    op.drop_index('ix_case_persons_person_role', table_name='case_persons')
    op.drop_table('case_persons')
    op.drop_index('ix_ai_runs_message_task_created', table_name='ai_extraction_runs')
    op.drop_table('ai_extraction_runs')
    op.drop_index('uq_agent_assignments_active_item', table_name='agent_assignments', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_index('ix_agent_assignments_agent_released', table_name='agent_assignments')
    op.drop_table('agent_assignments')
    op.drop_index('ix_volunteer_offer_skills', table_name='volunteer_offer_details', postgresql_using='gin')
    op.drop_table('volunteer_offer_details')
    op.drop_index('ix_user_role_user_incident', table_name='user_role_assignments')
    op.drop_table('user_role_assignments')
    op.drop_index('ix_trust_assessments_subject', table_name='trust_assessments')
    op.drop_table('trust_assessments')
    op.drop_index('ix_transport_offer_flags', table_name='transport_offer_details')
    op.drop_table('transport_offer_details')
    op.drop_index(op.f('ix_service_offer_details_service_category'), table_name='service_offer_details')
    op.drop_table('service_offer_details')
    op.drop_index('ix_risk_signals_incident_status', table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index('ix_retention_jobs_policy_status', table_name='retention_jobs')
    op.drop_table('retention_jobs')
    op.drop_index('ix_resource_offer_items_offer_catalog', table_name='resource_offer_items')
    op.drop_table('resource_offer_items')
    op.drop_index('ix_reports_incident_status_submitted', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_org_memberships_user_status', table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_table('money_offer_details')
    op.drop_index('ix_messages_conversation_provider_ts', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_household_members_person', table_name='household_members')
    op.drop_table('household_members')
    op.drop_index('uq_duplicate_candidates_pair', table_name='duplicate_candidates')
    op.drop_index('ix_duplicate_candidates_status_score', table_name='duplicate_candidates')
    op.drop_table('duplicate_candidates')
    op.drop_index('uq_conversation_participants_active', table_name='conversation_participants', postgresql_where=sa.text('left_at IS NULL'))
    op.drop_index('ix_conversation_participants_conv_joined', table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index('ix_cases_incident_status_priority', table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_agent_queue_items_dispatch', table_name='agent_queue_items')
    op.drop_table('agent_queue_items')
    op.drop_index('ix_access_events_entity', table_name='access_events')
    op.drop_index('ix_access_events_actor_occurred', table_name='access_events')
    op.drop_table('access_events')
    op.drop_index('ix_webhook_receipts_status_received', table_name='webhook_receipts')
    op.drop_table('webhook_receipts')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_resource_offers_incident_type_status', table_name='resource_offers')
    op.drop_table('resource_offers')
    op.drop_table('public_impact_snapshots')
    op.drop_index('ix_person_identifiers_person_primary', table_name='person_identifiers')
    op.drop_table('person_identifiers')
    op.drop_index('ix_notifications_status_scheduled', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('households')
    op.drop_index('ix_conversations_last_message_status', table_name='conversations')
    op.drop_index('ix_conversations_channel_thread_status', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_consents_person_purpose', table_name='consents')
    op.drop_table('consents')
    op.drop_table('roles')
    op.drop_index(op.f('ix_persons_name_dedupe_hmac'), table_name='persons')
    op.drop_table('persons')
    op.drop_index('ix_outbox_events_status_occurred', table_name='outbox_events')
    op.drop_index('ix_outbox_events_status_next_attempt', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_organizations_tax_id_hmac'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_need_catalog_parent_active', table_name='need_catalog')
    op.drop_table('need_catalog')
    op.drop_index('ix_locations_admin', table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_incidents_status_starts', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_idempotency_keys_expires_at'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_geo_divipola_department_code'), table_name='geo_divipola')
    op.drop_table('geo_divipola')
    op.drop_table('channels')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
